version: '3'

services:
  app:
    build: .
    container_name: my-node-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    restart: always
